// day18svelte/src/lib/Gugu.svelte
<script>
  let dan = "2"
  let disp = ""

  let myclick = () => {
      let idan = parseInt(dan)
      disp = ""
      for (let i = 1; i <= 9; i++) {
          disp += dan+"*"+i+"="+(idan*i)+"<br/>"
      }
  }

</script>

<style>
    #it{
        width: 30px;
    }
    table,td{
        border:1px solid;
    }
    div{
        height: 200px;
    }
</style>

<table >
    <tr>
        <td>출력단수</td>
        <td><input type="text" id="it" bind:value="{dan}" ></td>
    </tr>
    <tr>
        <td colspan="2">
            <input type="button" value="구구단출력" on:click={myclick} />
        </td>
    </tr>
    <tr>
        <td colspan="2">
            <div>{@html disp}</div>
        </td>
    </tr>

</table>

// day19vue/src/components/Gugu.vue
<script setup>
import { ref } from 'vue'

let dan = ref("2")
let disp = ref("__")

let myclick = () => {
  let idan = parseInt(dan.value)
  let txt = ""
  for (let i = 1; i <= 9; i++) {
    txt += idan+"*"+i+"="+(idan*i)+"<br/>"
  }


  disp.value = txt
}

</script>

<template>
  <table>
    <tr>
      <td>출력단수:</td>
      <td>
        <input type="text" v-model:="dan" />
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <input type="button" value="출력하기" @click="myclick" />
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <div v-html="disp"></div>
      </td>
    </tr>
  </table>

</template>

<style scoped>
input[type='text']{
  width: 30px;
}
table,td{
  border : 1px solid #ccc;
}
div{
  height: 200px;
}

</style>
