// day18svelte/src/lib/Life.svelte


<script>
    import { onMount, onDestroy, beforeUpdate, afterUpdate} from 'svelte'
    let msg = "Life Cycle"


    onMount(async() => {
        console.log('[Life] onMount')
    })

    onDestroy(async() => {
        console.log('[Life] onDestroy')
    })

    beforeUpdate(async() => {
      console.log('[Life] beforeUpdate')
    })

    afterUpdate(async() => {
        console.log('[Life] afterUpdate')
    })

</script>

<span>{msg}</span>

// day19vue/src/components/Life.vue
<script setup>
import {onBeforeUpdate, onMounted, onUpdated, ref} from 'vue'

const msg = ref("Life Cycle")

onMounted(() => {
  console.log("[Life]onMounted")
})
onBeforeUpdate(() => {
  console.log("[Life]onBeforeUpdate")
})
onUpdated(() => {
  console.log("[Life]onUpdated")
})

</script>

<template>
  <span>{{msg}}</span>

</template>

<style scoped>

</style>
