// day20react/src/Emp.jsx
import {useEffect, useState} from 'react'


function Emp() {
    const [e_id, setE_id] = useState("")
    const [e_name, setE_name] = useState("")
    const [e_gen, setE_gen] = useState("")
    const [e_addr, setE_addr] = useState("")

    const [list, setList] = useState(
        [
            {e_id: '1', e_name: '1', e_gen: '1', e_addr: '1'},
            {e_id: '2', e_name: '2', e_gen: '2', e_addr: '2'}
        ]
    )

    let fn_one = (e) => {
        let e_id = e.target.innerHTML;
        fetch('http://127.0.0.1/emp_one.ajax', {
            method: "POST",
            headers: {"Content-Type": "application/json"},
            body: JSON.stringify({e_id: e_id})
        })
            .then(response => response.json())
            .then(json => {
                console.log(json);
            })
    }

    let fn_list = () => {
        fetch('http://127.0.0.1/emp_list.ajax', {
            method: "POST",
            headers: {"Content-Type": "application/json"},
            body: JSON.stringify({menu: "짬뽕"})
        })
            .then(response => response.json())
            .then(json => {
                let list = json;
                setList(list);
                console.log(json.list);
            })
    }

    useEffect(() => {
        console.log("useEffect:onMount");
        fn_list();
    }, []);

    return (
        <>
            <table>
                <tbody>
                <tr>
                    <td>사번</td>
                    <td>이름</td>
                    <td>성별</td>
                    <td>주소</td>
                </tr>

                {list.map((vo, index) => (
                    <tr key={index}>
                        <td><a onClick={fn_one}>{vo.e_id}</a></td>
                        <td>{vo.e_name}</td>
                        <td>{vo.e_gen}</td>
                        <td>{vo.e_addr}</td>
                    </tr>
                ))}


                </tbody>
            </table>


            <table>
                <tbody>
                <tr>
                    <td>사번</td>
                    <td>
                        <input type="text" value={e_id} onChange={(e) => setE_id(e.target.value)}/>
                    </td>
                </tr>
                <tr>
                    <td>이름</td>
                    <td>
                        <input type="text" value={e_name} onChange={(e) => setE_name(e.target.value)}/>
                    </td>
                </tr>
                <tr>
                    <td>성별</td>
                    <td>
                        <input type="text" value={e_gen} onChange={(e) => setE_gen(e.target.value)}/>
                    </td>
                </tr>
                <tr>
                    <td>주소</td>
                    <td>
                        <input type="text" value={e_addr} onChange={(e) => setE_addr(e.target.value)}/>
                    </td>
                </tr>
                <tr>
                    <td colSpan="2">
                        <input type="button" value="추가"/>
                        <input type="button" value="수정"/>
                        <input type="button" value="삭제"/>
                    </td>
                </tr>
                </tbody>
            </table>
        </>
    )
}

export default Emp

// day18svelte/src/lib/Emp.svelte
<script>
    import {onMount} from "svelte";

    let mylist = [
        {'e_id': '1', 'e_name': '1', 'e_gen': '1', 'e_addr': '1'},
        {'e_id': '2', 'e_name': '2', 'e_gen': '2', 'e_addr': '2'}
    ]

    onMount(async () => {
        fn_list()
    })

    function fn_list() {
        fetch('http://127.0.0.1/emp_list.ajax', {
            method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify({menu: "짬뽕"})
        })

            .then(response => response.json())
            .then(json => {
                console.log(json.list);
                mylist = json.list;
            })
    }

    let vo = {'e_id': '_', 'e_name': '_', 'e_gen': '_', 'e_addr': '_'};

    let fn_add = () => {

        let param = vo
        fetch('http://127.0.0.1/emp_add.ajax', {
            method: "POST",
            headers: {"Content-Type": "application/json"},
                body: JSON.stringify(param)
            })
            .then(response => response.json())
            .then(json => {
                var cnt = json.cnt;
                if (cnt == 1) {
                    fn_list();
                    alert("정상적으로 추가했습니다");
                    vo.e_id = "";
                    vo.e_name = "";
                    vo.e_gen = "";
                    vo.e_addr = "";
                } else {
                    alert("추가도중 문제가 생겼씁니다");
                }

            })

    }
    let fn_mod = () => {

        let param = vo
        fetch('http://127.0.0.1/emp_mod.ajax', {
            method: "POST",
            headers: {"Content-Type": "application/json"},
                body: JSON.stringify(param)
            })
            .then(response => response.json())
            .then(json => {
                var cnt = json.cnt;
                if (cnt == 1) {
                    alert("정상적으로 수정했습니다");
                    fn_list()
                    vo.e_id = "";
                    vo.e_name = "";
                    vo.e_gen = "";
                    vo.e_addr = "";
                } else {
                    alert("수정도중 문제가 생겼씁니다")
                }
            })
    }

    let fn_del = () => {

        let param = vo
        fetch('http://127.0.0.1/emp.del.ajax', {
            method: "POST",
            headers: {"Content-Type": "application/json"},
                body: JSON.stringify(param)
            })
            .then(response => response.json())
            .then(json => {
                var cnt = json.cnt;
                if (cnt == 1) {
                    alert("정상적으로삭제했습니다");
                    fn_list()
                    vo.e_id = "";
                    vo.e_name = "";
                    vo.e_gen = "";
                    vo.e_addr = "";
                } else {
                    alert("삭제도중 문제가 생겼씁니다")
                }

            })

    }


        let fn_one = (e_id) => {
            fetch('http://127.0.0.1/emp_one.ajax', {
                method: "POST",
                headers: {"Content-Type": "application/json"},
                    body: JSON.stringify({e_id: e_id})
                })
                .then(response => response.json())
                .then(json => {
                    vo = json.vo
                })
        }

</script>
<style>
    table, td {
        border: 1px solid #ddd;
    }
</style>

<a on:click={fn_list}>ajax</a>

<table>
    <tr>
        <td>사번</td>
        <td>이름</td>
        <td>성별</td>
        <td>주소</td>
    </tr>

    {#each mylist as item}
        <tr>
            <td>{item.e_id}</td>
            <td>{item.e_name}</td>
            <td>{item.e_gen}</td>
            <td>{item.e_addr}</td>
        </tr>
    {/each}

    <!--{#each mylist as {e_id, e_name, e_gen, e_addr}}-->
    <!--    <tr>-->
    <!--        <td>{e_id}</td>-->
    <!--        <td>{e_name}</td>-->
    <!--        <td>{e_gen}</td>-->
    <!--        <td>{e_addr}</td>-->
    <!--    </tr>-->
    <!--{/each}-->
</table>

<table>
    <tr>
        <td>사번</td>
        <td>
            <input type="text" value="{vo.e_id}"/>
        </td>
    </tr>
    <tr>

        <td>이름</td>
        <td>
            <input type="text" bind:value="{vo.e_name}"/>
        </td>
    </tr>
    <tr>

        <td>성별</td>
        <td>
            <input type="text" bind:value="{vo.e_gen}"/>
        </td>
    </tr>
    <tr>

        <td>주소</td>
        <td>
            <input type="text" bind:value="{vo.e_addr}"/>
        </td>
    </tr>
    <tr>

        <td colspan="2">
            <input type="button" value="추가" on:click={fn_add}/>
            <input type="button" value="수정" on:click={fn_mod}/>
            <input type="button" value="삭제" on:click={fn_del}/>
        </td>
    </tr>
    <tr>
</table>
