// day19vue/src/components/Emp.vue

<script setup>
import {onMounted, ref} from 'vue'
import axios from "axios";

const mylist = ref([
  {"e_id":"1","e_name":"1","e_gen":"1","e_addr":"1"},
  {"e_id":"2","e_name":"2","e_gen":"2","e_addr":"2"}
])

const vo = ref({e_id:"_",e_name:"_",e_gen:"_",e_addr:"_"})

let fn_list = () => {
	axios.post('http://127.0.0.1/emp_list.ajax').then((resp)=>{
	    console.log(resp.data.list);
      mylist.value = resp.data.list;
	})
}

let fn_one = (e_id) => {
  const param ={
    e_id : e_id
  }

  axios.post('http://127.0.0.1/emp_one.ajax', param).then((resp)=>{
	    console.log(resp.data.vo);
      vo.value = resp.data.vo;
	})
}

let fn_add = () => {
  axios.post('http://127.0.0.1/emp_add.ajax', vo.value).then((resp) => {
    console.log(resp.data.cnt);
    let cnt = resp.data.cnt;
    if (cnt == 1) {
      alert("정상 추가");
      fn_list();
      vo.value.e_id = "";
      vo.value.e_name = "";
      vo.value.e_gen = "";
      vo.value.e_addr = "";
    } else {
      alert("추가 도중 문제발생")
    }
  })
}

let fn_mod = () => {
  axios.post('http://127.0.0.1/emp_mod.ajax', vo.value.e_id).then((resp) => {
    console.log(resp.data.cnt);
    let cnt = resp.data.cnt;
    if (cnt == 1) {
      alert("정상 수정");
      fn_list();
      vo.value.e_id = "";
      vo.value.e_name = "";
      vo.value.e_gen = "";
      vo.value.e_addr = "";
    } else {
      alert("수정 도중 문제발생")
    }
  })
}

let fn_del = () => {
  var flag = confirm("한번 지워진 데이터는 복구 불가합니다. \n 그래도 지우십니까?");
  if (!flag) return;
  axios.post('http://127.0.0.1/emp_del.ajax', vo.value).then((resp) => {
    console.log(resp.data.cnt);
    let cnt = resp.data.cnt;
    if (cnt == 1) {
      alert("정상 삭제");
      fn_list();
      vo.value.e_id = "";
      vo.value.e_name = "";
      vo.value.e_gen = "";
      vo.value.e_addr = "";
    } else {
      alert("삭제 도중 문제발생")
    }
  })
}

onMounted(() => {
  fn_list()
})

</script>

<template>
  <table>
    <tr>
      <td>사번</td>
      <td>이름</td>
      <td>성별</td>
      <td>주소</td>
    </tr>

    <tr v-for="(vo, index) in mylist" :key="index" >
      <td><a @click="fn_one(vo.e_id)">{{vo.e_id}}</a></td>
      <td>{{vo.e_name}}</td>
      <td>{{vo.e_gen}}</td>
      <td>{{vo.e_addr}}</td>
    </tr>

  </table>
  <table>
    <tr>
      <td>사번</td>
      <td><input type="text" v-model:="vo.e_id" /></td>
    </tr>
    <tr>
      <td>이름</td>
      <td><input type="text" v-model:="vo.e_name" /></td>
    </tr>
    <tr>
      <td>성별</td>
      <td><input type="text" v-model:="vo.e_gen" /></td>
    </tr>
    <tr>
      <td>주소</td>
      <td><input type="text" v-model:="vo.e_addr" /></td>
    </tr>
    <tr>
      <td colspan="2">
        <button @click="fn_add">추가</button>
        <button @click="fn_mod" >수정</button>
        <button @click="fn_del">삭제</button>
      </td>
    </tr>
  </table>

</template>

<style scoped>
table,td{
  border : 1px solid #ccc;
}
input[type=text]{
  width: 80px;
}
</style>

// day18svelte/src/lib/Emp.svelte
<script>
    import {onMount} from "svelte";

    let mylist = [
        {'e_id': '1', 'e_name': '1', 'e_gen': '1', 'e_addr': '1'},
        {'e_id': '2', 'e_name': '2', 'e_gen': '2', 'e_addr': '2'}
    ]

    onMount(async () => {
        fn_list()
    })

    function fn_list() {
        fetch('http://127.0.0.1/emp_list.ajax', {
            method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify({menu: "짬뽕"})
        })

            .then(response => response.json())
            .then(json => {
                console.log(json.list);
                mylist = json.list;
            })
    }

    let vo = {'e_id': '_', 'e_name': '_', 'e_gen': '_', 'e_addr': '_'};

    let fn_add = () => {

        let param = vo
        fetch('http://127.0.0.1/emp_add.ajax', {
            method: "POST",
            headers: {"Content-Type": "application/json"},
                body: JSON.stringify(param)
            })
            .then(response => response.json())
            .then(json => {
                var cnt = json.cnt;
                if (cnt == 1) {
                    fn_list();
                    alert("정상적으로 추가했습니다");
                    vo.e_id = "";
                    vo.e_name = "";
                    vo.e_gen = "";
                    vo.e_addr = "";
                } else {
                    alert("추가도중 문제가 생겼씁니다");
                }

            })

    }
    let fn_mod = () => {

        let param = vo
        fetch('http://127.0.0.1/emp_mod.ajax', {
            method: "POST",
            headers: {"Content-Type": "application/json"},
                body: JSON.stringify(param)
            })
            .then(response => response.json())
            .then(json => {
                var cnt = json.cnt;
                if (cnt == 1) {
                    alert("정상적으로 수정했습니다");
                    fn_list()
                    vo.e_id = "";
                    vo.e_name = "";
                    vo.e_gen = "";
                    vo.e_addr = "";
                } else {
                    alert("수정도중 문제가 생겼씁니다")
                }
            })
    }

    let fn_del = () => {

        let param = vo
        fetch('http://127.0.0.1/emp.del.ajax', {
            method: "POST",
            headers: {"Content-Type": "application/json"},
                body: JSON.stringify(param)
            })
            .then(response => response.json())
            .then(json => {
                var cnt = json.cnt;
                if (cnt == 1) {
                    alert("정상적으로삭제했습니다");
                    fn_list()
                    vo.e_id = "";
                    vo.e_name = "";
                    vo.e_gen = "";
                    vo.e_addr = "";
                } else {
                    alert("삭제도중 문제가 생겼씁니다")
                }

            })

    }


        let fn_one = (e_id) => {
            fetch('http://127.0.0.1/emp_one.ajax', {
                method: "POST",
                headers: {"Content-Type": "application/json"},
                    body: JSON.stringify({e_id: e_id})
                })
                .then(response => response.json())
                .then(json => {
                    vo = json.vo
                })
        }

</script>
<style>
    table, td {
        border: 1px solid #ddd;
    }
</style>

<a on:click={fn_list}>ajax</a>

<table>
    <tr>
        <td>사번</td>
        <td>이름</td>
        <td>성별</td>
        <td>주소</td>
    </tr>

    {#each mylist as item}
        <tr>
            <td>{item.e_id}</td>
            <td>{item.e_name}</td>
            <td>{item.e_gen}</td>
            <td>{item.e_addr}</td>
        </tr>
    {/each}

    <!--{#each mylist as {e_id, e_name, e_gen, e_addr}}-->
    <!--    <tr>-->
    <!--        <td>{e_id}</td>-->
    <!--        <td>{e_name}</td>-->
    <!--        <td>{e_gen}</td>-->
    <!--        <td>{e_addr}</td>-->
    <!--    </tr>-->
    <!--{/each}-->
</table>

<table>
    <tr>
        <td>사번</td>
        <td>
            <input type="text" value="{vo.e_id}"/>
        </td>
    </tr>
    <tr>

        <td>이름</td>
        <td>
            <input type="text" bind:value="{vo.e_name}"/>
        </td>
    </tr>
    <tr>

        <td>성별</td>
        <td>
            <input type="text" bind:value="{vo.e_gen}"/>
        </td>
    </tr>
    <tr>

        <td>주소</td>
        <td>
            <input type="text" bind:value="{vo.e_addr}"/>
        </td>
    </tr>
    <tr>

        <td colspan="2">
            <input type="button" value="추가" on:click={fn_add}/>
            <input type="button" value="수정" on:click={fn_mod}/>
            <input type="button" value="삭제" on:click={fn_del}/>
        </td>
    </tr>
    <tr>
</table>
