// day20react/src/Life.jsx
import {useEffect, useState} from 'react'

function Life() {
  const [msg, setMsg] = useState("Good Morning")

    const myclick = () => {
        setMsg("Good Evening");
    }
    useEffect(() => {
        console.log("useEffect:onMount");
        return () => {
            console.log("userEffect:onMount**")
        }
    }, []);
  return (
    <>
        <div>{msg}</div>
        <input type="button" onClick={myclick}/>
    </>
  )
}

export default Life

// day18svelte/src/lib/Life.svelte


<script>
    import { onMount, onDestroy, beforeUpdate, afterUpdate} from 'svelte'
    let msg = "Life Cycle"


    onMount(async() => {
        console.log('[Life] onMount')
    })

    onDestroy(async() => {
        console.log('[Life] onDestroy')
    })

    beforeUpdate(async() => {
      console.log('[Life] beforeUpdate')
    })

    afterUpdate(async() => {
        console.log('[Life] afterUpdate')
    })

</script>

<span>{msg}</span>
