// day18svelte/src/App.svelte
<script>
  import svelteLogo from './assets/svelte.svg'
  import viteLogo from '/vite.svg'
  import Counter from './lib/Counter.svelte'
  import Morning from './lib/Morning.svelte'
  import Lotto from "./lib/Lotto.svelte";
  import Gugu from "./lib/Gugu.svelte";
  import Phone from "./lib/Phone.svelte";
  import Life from "./lib/Life.svelte";
  import {afterUpdate, beforeUpdate, onDestroy, onMount} from "svelte";
  import Strike from "./lib/Strike.svelte";
  import Emp from "./lib/Emp.svelte";
  onMount(async() => {
    console.log('[App] onMount')
  })

  onDestroy(async() => {
    console.log('[App] onDestroy')
  })

  beforeUpdate(async() => {
    console.log('[App] beforeUpdate')
  })

  afterUpdate(async() => {
    console.log('[App] afterUpdate')
  })
</script>
<main>

  <div class="card">
    <Emp />
  </div>

</main>

<style>

</style>

// day19vue/src/App.vue
<script setup>
import HelloWorld from './components/HelloWorld.vue'
import Morning from "./components/Morning.vue";
import MorningReac from "./components/MorningReac.vue";
import Lotto from "./components/Lotto.vue";
import Gugu from "./components/Gugu.vue";
import Phone from "./components/Phone.vue";
import Life from "./components/Life.vue";
import {onBeforeUpdate, onMounted, onUpdated} from "vue";
import Strike from "./components/Strike.vue";
import Emp from "./components/Emp.vue";

onMounted(() => {
  console.log("[App]onMounted")
})
onBeforeUpdate(() => {
  console.log("[App]onBeforeUpdate")
})
onUpdated(() => {
  console.log("[App]onUpdated")
})

</script>

<template>
  <Emp/>
</template>

<style scoped>

</style>
